name: rl_repr_lab
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - python=3.7.3
  - pip=19.2.3
  - numpy=1.17.2
  - scipy=1.3.1
  - pandas=0.25.1
  - matplotlib=3.1.1
  - jupyter=1.0.0
  - tqdm=4.36.1
  - pytorch=1.2.0
  - hyperopt=0.1.2
  - pip:
    - gym==0.12.5
